image_config: &image_config
  IMAGE_NAME: ruby:3.1.4-node-cypress

version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202111-02
    environment:
      <<: *image_config

    steps:
      - checkout

      - run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

      - run: docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME .

      - run: docker push $DOCKERHUB_USERNAME/$IMAGE_NAME && sleep 10

      - store_artifacts:
          path: Dockerfile

workflows:
  version: 2
  update_image:
    jobs:
      - build
