image_config: &image_config
  IMAGE_NAME: ruby:2.7.4-node-cypress

version: 2
jobs:
  build:
    machine: true
    environment:
      <<: *image_config

    steps:
      - checkout

      - run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

      - run: docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME .

      - run: docker push $DOCKERHUB_USERNAME/$IMAGE_NAME && sleep 10

      - store_artifacts:
          path: Dockerfile

workflows:
  version: 2
  dockerfile_wizard:
    jobs:
      - build
