image_config: &image_config
  IMAGE_NAME: ruby:2.7.4-node-cypress

version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202111-02
    environment:
      <<: *image_config

    steps:
      - checkout

      - run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

      - run: docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME .

      - run: docker push $DOCKERHUB_USERNAME/$IMAGE_NAME && sleep 10

      - store_artifacts:
          path: Dockerfile

workflows:
  version: 2
  build_on_push:
    jobs:
      - build
  weekly_build:
    triggers:
      - schedule:
          cron: "0 2 * * 1"
          filters:
            branches:
              only: "master"
    jobs:
      - build