version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202111-02

    steps:
      - checkout

      - run: echo 'export RUBY_VERSION="$(cat .ruby-version)"' >> "$BASH_ENV"

      - run: echo 'export IMAGE_NAME="ruby:$RUBY_VERSION-node-cypress"' >> "$BASH_ENV"

      - run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

      - run: docker build --build-arg RUBY_VERSION=$RUBY_VERSION -t $DOCKERHUB_USERNAME/$IMAGE_NAME .

      - run: docker push $DOCKERHUB_USERNAME/$IMAGE_NAME && sleep 10

      - store_artifacts:
          path: Dockerfile

workflows:
  version: 2
  update_image:
    jobs:
      - build
