name: generate
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Fetch available Ruby versions from DockerHub
        run: |
          {
            echo 'VERSIONS<<EOF'
            curl 'https://hub.docker.com/v2/namespaces/cimg/repositories/ruby/tags?page_size=10' | jq -r '.results[].name' | grep -E '^[0-9\.]+$'
            echo EOF
          } >> "$GITHUB_ENV"
      - id: matrix
        run: |
          echo "Checking branches..."
          for version in $(echo "$VERSIONS"); do
            if git ls-remote --heads origin chore/ruby-$version | grep -q chore/ruby-$version; then
              echo " - Skipping $version, branch already exists."
              TMP=$(echo "$TMP" | sed "/^$version$/d")
            fi
          done

          echo "Set matrix output..."
          if [ -n "$TMP" ]; then
            TMP=$(echo "$TMP" | tr ' ' '\n' | jq -R . | jq -sc .)
          else
            TMP="[]"
          fi
          echo "Output: $TMP"

          echo "value=$TMP" >> $GITHUB_OUTPUT
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJSON(needs.setup.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.email "bot@planima.se"
          git config user.name "Planibot"
          git config push.autoSetupRemote true
      - run: |
          git checkout -b chore/ruby-${{ matrix.value }} && \
          echo "${{ matrix.value }}" > .ruby-version && \
          git commit -am "New Ruby version" && \
          git push
