name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - uses: actions/checkout@v4
      - name: list all PRs
        run: gh pr list
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: get ruby images tags
        run: curl "https://hub.docker.com/v2/namespaces/cimg/repositories/ruby/tags?page_size=100" | jq '.results[].name' | grep -E '"[0-9\.]+"$'
